version: "2.15.1"

networks:
  algafood-network:
    driver: bridge

services:
  algafood-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "docker"
    ports:
      - "3306:3306"
    networks:
      - algafood-network

  algafood-redis:
    build: ./redis
    image: algafood-redis
    networks:
      - algafood-network

  algafood-api:
    image: algafood-api
    command: ["/wait-for-it.sh", "algafood-mysql:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      DBHOST: algafood-mysql
      SPRING_SESSION_STORE_TYPE: redis
      SPRING_REDIS_HOST: algafood-redis
    networks:
      - algafood-network
    deploy:
      replicas: 2
    depends_on:
      - algafood-mysql

  algafood-nginx:
    build: ./nginx
    image: algafood-nginx
    ports:
      - "80:80"
    networks:
      - algafood-network
    depends_on:
      - algafood-api